### ISSUE TITLE
Disable kickforvip

### ISSUE THREAD

**Issue by YellowZaki** [Xephi/AuthMeReloaded#1001]
Some players are being randomly kicked with the message: A VIP player has joined the server when it was full!
I have added to the default group the permission authme.vip and it keeps happening. What can I do?
Thanks

**Comment by ljacqu** [comment]
Players with the permission node `authme.vip` may join a full server and someone without this permission will be kicked. If you want this feature disabled, do not assign the `authme.vip` permission to anyone. The default nodes `authme.player.*` and `authme.admin.*` don't include `authme.vip` so in case you use those, that's no issue.

Opped users get this permission by default, if it happens for other users we need to investigate this further. Please keep us updated.

Permissions: https://github.com/AuthMe/AuthMeReloaded/blob/master/docs/permission_nodes.md

**Comment by YellowZaki** [comment]
Anybody has the permission authme.vip, just OPs (by default). That's why I added authme.vip to all users.

**Comment by ljacqu** [comment]
My suggestion was to remove the authme.vip permission from everyone (including ops) since what you actually want is NOT for anyone to have this feature. Assigning the permission node to everyone should behave the same way, but semantically it's less clear.

Anyway, even with your setup no one should be kicked. To make sure that this comes from AuthMe and not from some other plugin, could I ask you to change the translation to something else and to make sure that the user will get this message? (This confirms that AuthMe is the source of the kick.)

In the meantime, I'll assign this issue to me and I'll see if I can reproduce it tomorrow.

**Comment by YellowZaki** [comment]
Yes, I'm sure the message comes from authme.
PD: my server player limit is 12 but the group member has the permission essentials.joinfullserver so there is no limit. (I can't change the 12 because of my server hosting)

**Comment by ljacqu** [comment]
Sorry for the late answer. In your config.yml, please set the following two things to enable logging to authme.log:

```yml
    # Log level: INFO, FINE, DEBUG. Use INFO for general messages,
    # FINE for some additional detailed ones (like password failed),
    # and DEBUG for debugging
    logLevel: 'DEBUG'
  ...
        # Copy AuthMe log output in a separate file as well?
        logConsole: true
```

Then please use the JAR given in https://github.com/ljacqu/AuthMeReloaded/tree/1001-vip-status-debug/samples (spigot or legacy, whichever you use). It will write a debug line each time a player joins. It would be interesting to see what comes out when the server is full and players join.
