### ISSUE TITLE
supportOldPasswordHash Not working

### ISSUE THREAD

**Issue by JhonatanPereira** [Xephi/AuthMeReloaded#1021]
supportOldPasswordHash option not working.
I've changed my hash algoritm to XFBCRYPT(Xenforo), my old was SHA256.
I turned "supportOldPasswordHash " to true, but AuthMe still not recognizing my SHA256 password
No errors in console, it just kicked me with wrong password message.
When I put a XFBCRYPT password in database, I can loggin normally.

Config: http://hastebin.com/yetewuzamo.http

**Comment by ljacqu** [comment]
Please check your config.yml, if your build is high enough (what's your /authme version?) you will find a new setting `legacyHashes` to which you can add your the old hash algorithms you still want to consider. 
https://github.com/Xephi/AuthMeReloaded/issues/850#issuecomment-260175766

**Comment by JhonatanPereira** [comment]
I'm using 5.2-SNAPSHOT, the latest build in spigotmc
Where I can download the build with this legacyHashes option?

**Comment by ljacqu** [comment]
From our Jenkins at http://ci.xephi.fr/job/AuthMeReloaded

**Comment by JhonatanPereira** [comment]
Now I'm using the latest build, I've put SHA256 in legacyHashes option, and still not working.
When I put XFBCRYPT password in database, I can login normally

updated config: http://hastebin.com/fipisebedu.bash

**Comment by ljacqu** [comment]
Could you please give step by step instructions to reproduce this? Here's what I've tried:

### Register password with SHA256
With config.yml:
```yaml
        passwordHash: 'SHA256'
        doubleMD5SaltLength: 8
        legacyHashes: []
```

- `/register test1234`

### Change to XFBCRYPT with SHA256 as legacy hash
With config.yml:
```yaml
        passwordHash: 'XFBCRYPT'
        doubleMD5SaltLength: 8
        legacyHashes:
        - SHA256
```

- `/authme reload`
- `/login test1234`

--> Login successful, password is changed to XFBCRYPT in database.
