### ISSUE TITLE
"Please register": remove individual message for each registration type?

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#1055]
Request for comments—@DNx5 @games647 @Gnat008 @koca2000 @sgdc3 @Twonox (alphabetical)

PR [#190](https://github.com/AuthMe/AuthMeReloaded/pull/190) introduced an individual message for each register variant:
```yaml
reg_msg: '&3Please, register to the server with the command "/register <password> <ConfirmPassword>"'
reg_no_repeat_msg: '&3Please, register to the server with the command "/register <password>"'
reg_email_msg: '&3Please, register to the server with the command "/register <email> <confirmEmail>"'
reg_email_no_repeat_msg: '&3Please, register to the server with the command "/register <email>"'
reg_psw_email_msg: '&3Please, register to the server with the command "/register <password> <email>"'
```

I would like to undo this. It's [not very straightforward to determine the message key to use](https://github.com/AuthMe/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/util/Utils.java#L73) and various other messages also need to be adapted (or, they would also need 5 variants): `reg_voluntarily` and `usage_reg`.

Suggestions are welcome how this is best handled. My proposition is the following:
- keep all messages with /register only once (default to /register &lt;password> &lt;confirmPassword>)
- create a Wiki page that lists the messages that need to be changed (and that explains the different variants we have; I think it would be nice to offer an explanation for email registration anyway).

Thoughts?

If one message gets accepted it would be best to still do this in 5.2 -> otherwise we release a version with tons of messages that will disappear in a subsequent version.
