### ISSUE TITLE
Unable to send mail after AuthMe settings, prompting email to the following server failed

### ISSUE THREAD

**Issue by patqian** [Xephi/AuthMeReloaded#1075]
Foxmail settings can normally send letters.
Unable to send mail after AuthMe settings, prompting email to the following server failed

### Steps/models to reproduce:
In AuthMe Version: 3.3.3 configuration can send mail.

### Environment description
Standalone server/, SQLite

### AuthMe build number:
AuthMe-5.2-SNAPSHOT-spigot

### Configuration:

```YAML
Email:
 # Email SMTP server host
 mailSMTP: 106.185.35.98
 # Email SMTP server port
 mailPort: 25
 # Email account that send the mail
 mailAccount: 'mc@77mc.com'
 # Email account password
 mailPassword: '123456'
 # Custom SenderName, that replace the mailAccount name in the email
 mailSenderName: ''
 # Random password length
 RecoveryPasswordLength: 8
 # Email subject of password get
 mailSubject: 'Your new AuthMe password'
 # Like maxRegPerIp but with email
 maxRegPerEmail: 1
 # Recall players to add an email?
 recallPlayers: false
 # Delay in minute for the recall scheduler
 delayRecall: 5
 # Blacklist these domains for emails
 emailBlacklisted:
 - 10minutemail.com
 # WhiteList only these domains for emails
 emailWhitelisted: []
 # Do we need to send new password draw in an image?
 generateImage: false
 # The email OAuth 2 token (leave empty if not used)
 emailOauth2Token: ''
```

Server output prompt:
`[AuthMe] Failed to send a mail to [mc77@163.com]: [EmailException]: Sending the email to the following server failed : 106.185.35.98:25 `

**Comment by ljacqu** [comment]
Do you have logging to authme.log enabled? If not, please enable it and share the full error from authme.log when sending an email fails. This helps will tell us _why_ the email can't be sent. Thanks

**Comment by sgdc3** [comment]
@patqian

**Comment by patqian** [comment]
Authme.log has been uploaded
[authme.log.txt](https://github.com/Xephi/AuthMeReloaded/files/751737/authme.log.txt)

**Comment by patqian** [comment]
@ljacqu @sgdc3

**Comment by sgdc3** [comment]
@ljacqu http://stackoverflow.com/questions/16115453/javamail-could-not-convert-socket-to-tls-gmail It seems related to antivirus/firewall settings.

**Comment by patqian** [comment]
@sgdc3 Test AuthMe3.3.3 version on the same server can send mail, AuthMe5.2 version can not send mail

**Comment by ljacqu** [comment]
Thanks for the feedback; I will check this.

**Comment by ljacqu** [comment]
I used to have a way to reproduce this on my machine locally but this is no longer the case. Let's create a branch where we add the 3.4 mail implementation to conduct some tests.

**Comment by ljacqu** [comment]
@patqian Could I ask you to use the JAR from https://github.com/AuthMe/AuthMeReloaded/tree/1075-mail-send-issues/samples ? (Legacy if you're using an old server version, otherwise spigot). 

This JAR has two commands:
- `/authme debug mail` which will send a test mail the way we currently do it ("the 5.2 way")
- `/authme debug oldmail` sends a test mail "the 3.4 way"

On my machine, both variants work. These commands work if you log in as a player and you have an email set to your account. If not you can run it from console using `/authme debug mail your.email@example.com` and `/authme debug oldmail custom-username`. The arguments aren't the same, unfortunately.

**Comment by patqian** [comment]
/authme debug mail  error
/authme debug oldmail  effective
[Uploading authmelog.zip…]()

**Comment by patqian** [comment]
@ljacqu

**Comment by patqian** [comment]
/authme debug mail error
/authme debug oldmail effective
[authme.txt](https://github.com/Xephi/AuthMeReloaded/files/790684/authme.txt)

**Comment by ljacqu** [comment]
Hi @patqian, sorry for the wait. I need to ask you to download the JAR at https://github.com/AuthMe/AuthMeReloaded/tree/1075-mail-send-issues/samples one last time and to try the following:

- /authme debug mail
- /authme debug mail2
- /authme debug oldmail

I'm very sure that "authme debug mail2" will work now, but I wonder if "authme debug mail" would work.
Once we get your feedback it will be possible to fix this in the real AuthMe JAR, hopefully once and for all! I'm really grateful for your feedback.

**Comment by patqian** [comment]
/authme debug mail error
/authme debug mail2 effective
/authme debug oldmail effective

![23](https://cloud.githubusercontent.com/assets/18672636/23339309/8ebdbef6-fc5a-11e6-8927-2086a3333e6b.png)
[authme.txt](https://github.com/Xephi/AuthMeReloaded/files/801915/authme.txt)
HI @ljacqu

**Comment by ljacqu** [comment]
Thanks @patqian! While I'm writing the fix, may I ask for one last test?

With the following in your config.yml:
```yaml
 mailPort: 465
```

any better luck using /authme debug mail?

**Comment by patqian** [comment]
mailPort: 465
/authme debug mail error
/authme debug mail2 error
/authme debug oldmail error
[authme.txt](https://github.com/Xephi/AuthMeReloaded/files/801958/authme.txt)

![12](https://cloud.githubusercontent.com/assets/18672636/23339864/0a960f5a-fc66-11e6-979d-cf7e94c179a1.png)

HI @ljacqu

**Comment by ljacqu** [comment]
Hi @patqian, last question, what about 587? I promise my next answer will be to announce the fix. :P Sorry for all the back and forth.

**Comment by patqian** [comment]
mailPort: 587
/authme debug mail error
/authme debug mail2 error
/authme debug oldmail error
![12](https://cloud.githubusercontent.com/assets/18672636/23339944/bd7a3e10-fc67-11e6-8814-bb1c89030a75.png)
[authme.txt](https://github.com/Xephi/AuthMeReloaded/files/801970/authme.txt)

**Comment by patqian** [comment]
Hi @ljacqu

**Comment by ljacqu** [comment]
Hi @patqian, thank you so much for the information and for your patience! 

The fix is now available in build nr. 1572 or above: http://ci.xephi.fr/job/AuthMeReloaded/ (or, if it's not done yet, available at https://github.com/AuthMe/AuthMeReloaded/tree/1075-mail-jars/samples )

A new option will appear in config.yml first time you run the JAR. Please set it to false:
```yml
Email:
   ...
   useTls: false
```

May I ask you for a quick feedback whether it works? (/authme debug mail)
