### ISSUE TITLE
Authme Cant save QuitLocation

### ISSUE THREAD

**Issue by Bodyash** [Xephi/AuthMeReloaded#146]
Video: https://youtu.be/-qQ8B7iEbgk
I'm Logging in.
Then i go to the groud from the roof.
Logout (disconnect, sessions disabled)
connecting again (i'm at the ground)
/l password
Teleporting back to my previous location o_O
I think new QuitLocation doesn`t saving to my MYSQL

http://pastebin.com/dg7RyScw (my config file)

**Comment by sgdc3** [comment]
Are you using latest dev version?

**Comment by Bodyash** [comment]
yeap, latest.

**Comment by sgdc3** [comment]
does it happen with sqlite?

**Comment by Bodyash** [comment]
doent tested. Can`t move my mySQL to SQLLite

**Comment by sgdc3** [comment]
Try with this:
```YAML
DataSource:
  mySQLColumnName: username
  mySQLTablename: authme
  mySQLUsername: root
  backend: mysql
  mySQLColumnLastLogin: lastlogin
  mySQLDatabase: authme
  mySQLPort: '3306'
  mySQLColumnIp: ip
  mySQLHost: 127.0.0.1
  mySQLColumnPassword: password
  mySQLPassword: 'password'
  caching: true
  mySQLlastlocX: x
  mySQLlastlocY: y
  mySQLlastlocZ: z
  mySQLlastlocWorld: world
  mySQLColumnEmail: email
  mySQLColumnId: id
  mySQLColumnLogged: isLogged
  mySQLRealName: realname
GroupOptions:
  UnregisteredPlayerGroup: ''
  RegisteredPlayerGroup: ''
  Permissions:
    PermissionsOnJoin: []
settings:
  sessions:
    enabled: false
    timeout: 5
    sessionExpireOnIpChange: true
  restrictions:
    allowChat: false
    allowCommands:
    - /login
    - /register
    - /l
    - /reg
    - /passpartu
    - /email
    - /captcha
    maxRegPerIp: 2
    maxNicknameLength: 16
    ForceSingleSession: true
    ForceSpawnLocOnJoinEnabled: false
    SaveQuitLocation: true
    AllowRestrictedUser: false
    AllowedRestrictedUser: []
    kickNonRegistered: false
    kickOnWrongPassword: false
    teleportUnAuthedToSpawn: false
    minNicknameLength: 4
    allowMovement: false
    timeout: 60
    allowedNicknameCharacters: '[a-zA-Z0-9_]*'
    allowedMovementRadius: 100
    enablePasswordVerifier: true
    ProtectInventoryBeforeLogIn: false
    displayOtherAccounts: false
    ForceSpawnOnTheseWorlds:
    - Empty
    banUnsafedIP: false
    spawnPriority: authme,essentials,multiverse,default
    maxLoginPerIp: 0
    maxJoinPerIp: 0
    noTeleport: false
    allowedPasswordCharacters: '[\x21-\x7E]*'
  GameMode:
    ForceSurvivalMode: false
    ResetInventoryIfCreative: false
    ForceOnlyAfterLogin: true
  security:
    minPasswordLength: 4
    unLoggedinGroup: unLoggedinGroup
    passwordHash: SHA256
    doubleMD5SaltLength: 8
    supportOldPasswordHash: false
    unsafePasswords: []
  registration:
    enabled: true
    messageInterval: 10
    force: true
    enableEmailRegistrationSystem: false
    doubleEmailCheck: false
    forceKickAfterRegister: false
    forceLoginAfterRegister: false
  unrestrictions:
    UnrestrictedName: []
  messagesLanguage: ru
  forceCommands: []
  forceCommandsAsConsole: []
  forceRegisterCommands: []
  forceRegisterCommandsAsConsole: []
  useWelcomeMessage: true
  broadcastWelcomeMessage: false
  delayJoinMessage: false
  applyBlindEffect: false
ExternalBoardOptions:
  mySQLColumnSalt: ''
  mySQLColumnGroup: ''
  nonActivedUserGroup: -1
  mySQLOtherUsernameColumns: []
  bCryptLog2Round: 10
  phpbbTablePrefix: phpbb_
  phpbbActivatedGroupId: 2
  wordpressTablePrefix: wp_
permission:
  EnablePermissionCheck: false
BackupSystem:
  ActivateBackup: false
  OnServerStart: false
  OnServerStop: false
  MysqlWindowsPath: C:\\Program Files\\MySQL\\MySQL Server 5.6\\
Passpartu:
  enablePasspartu: false
Security:
  SQLProblem:
    stopServer: true
  ReloadCommand:
    useReloadCommandSupport: true
  console:
    noConsoleSpam: false
    removePassword: true
    logConsole: false
  captcha:
    useCaptcha: false
    maxLoginTry: 5
    captchaLength: 5
Converter:
  Rakamak:
    fileName: users.rak
    useIP: false
    ipFileName: UsersIp.rak
  CrazyLogin:
    fileName: accounts.db
Email:
  mailSMTP: smtp.gmail.com
  mailPort: 465
  mailAccount: ''
  mailPassword: ''
  mailSenderName: ''
  RecoveryPasswordLength: 8
  mailSubject: Your new AuthMe Password
  maxRegPerEmail: 1
  recallPlayers: false
  delayRecall: 5
  mailText: 'Dear <playername>, \n\n This is your new AuthMe password for the server
    \n\n <servername> : \n\n <generatedpass>\n\nDo not forget to change password after
    login! \n /changepassword <generatedpass> newPassword'
  emailBlacklisted:
  - 10minutemail.com
  emailWhitelisted: []
  generateImage: true
Hooks:
  multiverse: true
  chestshop: true
  bungeecord: false
  disableSocialSpy: true
  useEssentialsMotd: false
  customAttributes: false
Purge:
  useAutoPurge: false
  daysBeforeRemovePlayer: 60
  removePlayerDat: false
  removeEssentialsFile: false
  defaultWorld: world
  removeLimitedCreativesInventories: false
  removeAntiXRayFile: false
  removePermissions: false
Protection:
  enableProtection: false
  countries:
  - US
  - GB
  enableAntiBot: false
  antiBotSensibility: 5
  antiBotDuration: 10
  countriesBlacklist:
  - A1
VeryGames:
  enableIpCheck: false
```
