### ISSUE TITLE
Issue with special characters

### ISSUE THREAD

**Issue by MiLk** [Xephi/AuthMeReloaded#206]
I have installed AuthMeReloaded on my Spigot server, but I have an issue with the french translation.

When the server start, it replaces the content of the `plugins/AuthMe/messages_fr.yml` file and replace all the special characters by hexadecimal code.

Instead of https://github.com/Xephi/AuthMeReloaded/blob/master/src/main/resources/messages_fr.yml, I get the following:
```yaml
# Traduction par: André
unknown_user: "&fUtilisateur non enregistr\xc3\xa9"
unsafe_spawn: "&fT\xc3\xa9l\xc3\xa9portation dans un endroit s\xc3\xbbr"
not_logged_in: "&cNon connect\xc3\xa9!"
reg_voluntarily: '&fVous venez d''arriver? faites un "/register motdepasse confirmermotdepasse"'
usage_log: '&cUtilisez: /login motdepasse'
wrong_pwd: '&cMauvais MotdePasse'
unregistered: "&cCe compte a \xc3\xa9t\xc3\xa9 supprim\xc3\xa9!"
reg_disabled: "&cL'enregistrement est d\xc3\xa9sactiv\xc3\xa9"
valid_session: "&cVous \xc3\xaates authentifi\xc3\xa9"
login: "&cConnection effectu\xc3\xa9e!"
vb_nonActiv: '&fCe compte n''est pas actif, consultez vos emails!'
user_regged: "&cCe nom est deja utilis\xc3\xa9.."
usage_reg: '&cUtilisez la commande /register motdepasse confirmermotdepasse'
...
```

What do I do wrong?

The server is running with the following parameter: `-DFiles.encoding=UTF8`.

Server version: `This server is running CraftBukkit version git-Spigot-fdc1440-53fac9f (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)`
AuthMe version: `5.0-beta3`
Java version: 
```
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```
