### ISSUE TITLE
problem with mysql when restart minecraft server

### ISSUE THREAD

**Issue by patrikmen** [Xephi/AuthMeReloaded#21]
hi, i have big problem when restart minecraft server.

i configure config.yml to work with mysql and i develop a module for drupal where the user register his account and set minecraft password. https://github.com/patrikmen/minelogin

work all perfectly, but if i restart my minecraft server table drop user data... not all... but only player don't have register a password.

it's a big problem. i don't know why drop data.

this is my config.yml of authme reloaded file:
```
# 
#  backend: mysql
DataSource:
  mySQLColumnName: username
  mySQLTablename: minelogin
  mySQLUsername: ********
  backend: mysql
  mySQLColumnLastLogin: lastlogin
  mySQLDatabase: **********
  mySQLPort: '3306'
  mySQLColumnIp: ip
  mySQLHost: 127.0.0.1
  mySQLColumnPassword: minepass
  mySQLPassword: *******
  caching: true
  mySQLlastlocX: x
  mySQLlastlocY: y
  mySQLlastlocZ: z
  mySQLlastlocWorld: world
  mySQLColumnEmail: mail
  mySQLColumnId: id
  mySQLColumnLogged: isLogged
GroupOptions:
  UnregisteredPlayerGroup: umani
  RegisteredPlayerGroup: umani
  Permissions:
    PermissionsOnJoin: []
settings:
  sessions:
    enabled: false
    timeout: 120
    sessionExpireOnIpChange: true
  restrictions:
    allowChat: false
    allowCommands:
    - /login
    - /l
    maxRegPerIp: 3
    maxNicknameLength: 20
    ForceSingleSession: true
    ForceSpawnLocOnJoinEnabled: false
    SaveQuitLocation: false
    AllowRestrictedUser: false
    AllowedRestrictedUser:
    - playername;127.0.0.1
    kickNonRegistered: false
    kickOnWrongPassword: false
    teleportUnAuthedToSpawn: false
    minNicknameLength: 3
    allowMovement: false
    timeout: 120
    allowedNicknameCharacters: '[a-zA-Z0-9_]*'
    allowedMovementRadius: 100
    enablePasswordVerifier: true
    ProtectInventoryBeforeLogIn: false
    displayOtherAccounts: true
    ForceSpawnOnTheseWorlds:
    - world
    - world_nether
    - world_the_end
    banUnsafedIP: false
    spawnPriority: essentials,authme,multiverse,default
    maxLoginPerIp: 0
    maxJoinPerIp: 0
    noTeleport: false
  GameMode:
    ForceSurvivalMode: false
    ResetInventoryIfCreative: false
    ForceOnlyAfterLogin: false
  security:
    minPasswordLength: 4
    unLoggedinGroup: unLoggedinGroup
    passwordHash: SHA512
    doubleMD5SaltLength: 8
    supportOldPasswordHash: false
    unsafePasswords: []
  registration:
    enabled: false
    messageInterval: 5
    force: true
    enableEmailRegistrationSystem: false
    doubleEmailCheck: false
    forceKickAfterRegister: false
    forceLoginAfterRegister: true
  unrestrictions:
    UnrestrictedName: []
  messagesLanguage: en
  forceCommands: []
  forceCommandsAsConsole: []
  useWelcomeMessage: true
  broadcastWelcomeMessage: false
  delayJoinMessage: false
ExternalBoardOptions:
  mySQLColumnSalt: ''
  mySQLColumnGroup: ''
  nonActivedUserGroup: -1
  mySQLOtherUsernameColumns: []
  bCryptLog2Round: 10
  phpbbTablePrefix: phpbb_
  phpbbActivatedGroupId: 2
  wordpressTablePrefix: wp_
permission:
  EnablePermissionCheck: false
BackupSystem:
  ActivateBackup: false
  OnServerStart: false
  OnServerStop: false
  MysqlWindowsPath: C:\\Program Files\\MySQL\\MySQL Server 5.1\\
Passpartu:
  enablePasspartu: false
Security:
  SQLProblem:
    stopServer: true
  ReloadCommand:
    useReloadCommandSupport: true
  console:
    noConsoleSpam: false
    removePassword: false
  captcha:
    useCaptcha: false
    maxLoginTry: 5
    captchaLength: 5
Converter:
  Rakamak:
    fileName: users.rak
    useIP: false
    ipFileName: UsersIp.rak
Email:
  mailSMTP: smtp.gmail.com
  mailPort: 465
  mailAccount: my_email
  mailPassword: mypass
  mailSenderName: administration
  RecoveryPasswordLength: 8
  mailSubject: Your new AuthMe Password
  mailText: 'Dear <playername>, <br /><br /> This is your new AuthMe password for
    the server <br /><br /> <servername> : <br /><br /> <generatedpass><br /><br />Do
    not forget to change password after login! <br /> /changepassword <generatedpass>
    newPassword'
  maxRegPerEmail: 1
  recallPlayers: false
  delayRecall: 5
Hooks:
  multiverse: true
  chestshop: true
  bungeecord: false
  notifications: true
  disableSocialSpy: true
  useEssentialsMotd: false
Performances:
  useMultiThreading: true
Purge:
  useAutoPurge: false
  daysBeforeRemovePlayer: 60
  removePlayerDat: false
  removeEssentialsFile: false
  defaultWorld: world
  removeLimitedCreativesInventories: false
  removeAntiXRayFile: false
Protection:
  enableProtection: false
  countries:
  - US
  - GB
  countriesBlacklist:
  - A1
  enableAntiBot: false
  antiBotSensibility: 5
  antiBotDuration: 10
VeryGames:
  enableIpCheck: false


```
p.s.:i use this to reload database for authme:
http://dev.bukkit.org/bukkit-plugins/simplecommandscheduler
with config file:

```
schedule:
  120:
  - 'authme reload'
```
