### ISSUE TITLE
Add pepper support

### ISSUE THREAD

**Issue by samvv** [Xephi/AuthMeReloaded#238]
If I'm correct, it currently isn't possible to log in with Joomla because AuthMe does not support salted passwords. This is a shame, because it would be a very nice feature.

Maybe add an entry to `config.yml` like this?

````yml
security:
  - ...
  - salt: 'YOUR_SALT_SECRET'
  - ...
````

For example, Joomla's salt is stored in `configuration.php` at `$secrect = 'YOUR_SALT_SECRET';`. Adding it to `security.salt` in `config.yml` would make it possible for AuthMe to correcly hash the password.

That or I'm missing something.
