### ISSUE TITLE
Translate help strings

### ISSUE THREAD

**Issue by xyblues** [Xephi/AuthMeReloaded#293]
I want to change all AUTHMERELOADED help.
Because I come from China...
I can help you translate.
thank
Like this.
/authme help [query] : View help
/authme help [查询] : 查看帮助
/authme register <player> <password> : Register a player
/authme register <玩家> <密码> : 注册一个玩家
/authme unregister <player> : Unregister a player
/authme unregister <玩家> : 反注册一个玩家

**Comment by sgdc3** [comment]
Ah! Sorry I misunderstood your request ;)

**Comment by xyblues** [comment]
It's nothing.But i not need it immediately.This can come slowly

**Comment by Xephi** [comment]
It will be added into translation message in the future, it's a new feature imported from an another project that doesn't support translation :p stay tuned :)

**Comment by ljacqu** [comment]
What would be nice if a lot is translatable is that it defaults to English if the message isn't present. Currently an error message appears, which isn't very useful for the typical user.

**Comment by ljacqu** [comment]
A few thoughts on this. I don't think it's a good idea to introduce new `MessageKey` entries for each and every help section as this will be huge. I'd much rather see this use some sort of dynamic keys. 

Right now when `/help` is fired we map the labels to a `CommandDescription` and read the description, permission, etc. from there. If we look at two command descriptions as an example:

```java
// for /email
	.labels("email")
	.description("Email command")
	.detailedDescription("The AuthMeReloaded Email command base.")

// for /authme unregister
	.parent(AUTHME_BASE)
	.labels("unregister", "unreg", "unr")
	.description("Unregister a player")
	.detailedDescription("Unregister the specified player.")
	.withArgument("player", "Player name", false)
	.permission(AdminPermission.UNREGISTER)
```

We always have the labels: "email" for /email, "authme unregister" for /authme unregister (when visiting the parent as well). This allows us to have sections in some message file (the existing messages_x.yml files, or rather new ones?):

```yml
help:
    email:
       description: 'Translated description for /email'
       detailedDescription: 'blabla'
    authme:
        unregister:
            description: 'Translated description for /authme unregster'
```

Or maybe the block style is nicer (they correspond to the same structure in YAML):
```yml
help:
   email:
       description: 'Translated description'
   authme.unregister:
       description: 'Translation for /authme unregister'
```

Could also have some form of `help.common` or `common` (if help messages go in a separate file) to make titles like "Permission" translatable. This would of course not be dynamic.

One open question is how to define arguments, whether their key should be based on their name, so e.g. `help.authme.unregister.argument.player` or if it should be a list without names (so `help.authme.unregister.argument[0]`).
