### ISSUE TITLE
Error with encoding. Not work russian names players. 

### ISSUE THREAD

**Issue by Mabus13** [Xephi/AuthMeReloaded#458]
MySQL UTF-8
ubuntu locale utf-8
All russian chars in DB visible only as ? like вадим = ?????

**Comment by Mabus13** [comment]
allowedNicknameCharacters: '[а-яА-Яa-zA-Z0-9_]*'

**Comment by ljacqu** [comment]
Personally, I wouldn't recommend using non-ASCII characters for usernames or passwords. Even if we can fix this issue here it's highly probable you'll encounter another issue at some other point, or that some data will be lost later on (say, if you or your host migrate some component).

**Comment by Mabus13** [comment]
I full translate my server in russian. For stupid russian schoolers.  They need russian chars in they names. =))) Lost data not mean for me.
p.s. password use only eng.

**Comment by Mabus13** [comment]
I lost maximum 20 accounts data. All other account english names. Because ???, ????, ?????... names block to reg all russian names same length.

I thiink it realy need to fix, because it error encoding same for other not eng languages.

**Comment by Dimatert9** [comment]
Обидно ведь (

**Comment by Mabus13** [comment]
Seek in source code functions what convert encoding for name. 99% here mistake arguments and after "converting" chars lost they data and replaced ????

**Comment by games647** [comment]
Does utf-8 include Russian characters. Maybe the connection to the database is not encoded correctly

**Comment by games647** [comment]
Could you test it? I tried to explicitly set utf-8 encoding. Maybe this will fix it.

**Comment by Mabus13** [comment]
I havent API for compile it, please can you compile it for me and it test fix it or not. chervanenko@gmail.com

**Comment by DNx5** [comment]
@Mabus13 
http://ci.xephi.fr/job/AuthMeReloaded/696/

**Comment by Mabus13** [comment]
@DNx5 Thank you! But 1,7mb why so fat >_< Testing.....

**Comment by Mabus13** [comment]
Not work T_T i try configure to work with my database. But geeat always same result: 

[19:58:26] [Server thread/INFO]: [AuthMe] Enabling AuthMe v5.2-SNAPSHOT-b696
[19:58:26] [Server thread/INFO]: [AuthMe] Loading Configuration File...
[19:58:26] [Server thread/INFO]: [AuthMe] Set Language to: en
[19:58:26] [Server thread/WARN]: [AuthMe] Can't load the configuration file... Something went wrong. To avoid security issues the server will shut down!
[19:58:26] [Server thread/WARN]: [AuthMe] Can't perform a Backup: disabled in configuration. Cause of the Backup: STOP
[19:58:26] [Server thread/INFO]: [AuthMe] Waiting for 0 tasks to finish
[19:58:26] [Server thread/INFO]: [AuthMe] AuthMe 5.2-SNAPSHOT-b696 disabled!

**Comment by Mabus13** [comment]
I try delete old config, and create "new". But after edit mysql setings i have result above.

**Comment by games647** [comment]
@Mabus13 Could add this to your configuration and restart the server so we can see the error message:

```yaml
Security:
    SQLProblem:
        # Stop the server if we can't contact the sql database
        # Take care with this, if you set that to false,
        # AuthMe automatically disable and the server is not protected!
        stopServer: true
    ReloadCommand:
        # /reload support
        useReloadCommandSupport: true
    console:
        # Prints error stacktraces to the console
        logConsole: true
```
