### ISSUE TITLE
Multiple lines in message files

### ISSUE THREAD

**Issue by JHXSMatthew** [Xephi/AuthMeReloaded#476]
Hi,

Could you guys add line changing char '\n' to implement a "multiple lines" message ?

say :
reg_msg: '&3Please,  register to the server with the command "/register <password> <ConfirmPassword>"'
It shows like 
Please,  register to the server with the command "/register <password> <ConfirmPassword>

Multiple lines:
reg_msg: '&3Please,  \n register to the server with the command "/register <password> <ConfirmPassword>"'
It shows like 
Please,  
register to the server with the command "/register <password> <ConfirmPassword>

Cheers
Matt

**Comment by games647** [comment]
It already works. Just wrap it into a new line:

![Authme-Line](http://i.imgur.com/YxfsagB.png)

So in your case:

```yaml
login_msg: '&cPlease, login with the command "/login <password>"'
reg_msg: '&3Please, 
    
    register to the server with the command "/register"'
reg_email_msg: '&3Please, register to the server with the command "/register <email> <confirmEmail>"'
```
