### ISSUE TITLE
authme email

### ISSUE THREAD

**Issue by MCG-server** [Xephi/AuthMeReloaded#509]
I put everything I've done everything but no email does not come to me as I do? new versions come out of authme - reloaded ?

**Comment by sgdc3** [comment]
@MCG-server What's your version atm?

**Comment by MCG-server** [comment]
The version of my authme is 5.0 beta 3

**Comment by MCG-server** [comment]
version of my sever is 1.8

**Comment by MCG-server** [comment]
@sgdc3 help me please

**Comment by ljacqu** [comment]
Stay patient

**Comment by MCG-server** [comment]
@ljacqu  @sgdc3  @timvisee  @irobin591  @Maxetto  but will release another version of authme -reload ?? please help me to set SMTP ( that works ) , I do not send the email so it's pointless

**Comment by MCG-server** [comment]
@sgdc3  @ljacqu  
I have the same problem NickFirenzo you can explain to me how you have helped him risolovere this bug ??

**Comment by sgdc3** [comment]
@MCG-server You need to update your version: http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.2-SNAPSHOT-spigot.jar

**Comment by MCG-server** [comment]
@sgdc3  

Then what should I do after installing the updated version

**Comment by sgdc3** [comment]
It should work if the config is correct and no errors are shown in the console ;)

**Comment by MCG-server** [comment]
but you are the creator of authme ?? 
I'm configuring the plugin

**Comment by MCG-server** [comment]
@sgdc3 how do I configure the SMTP always from config.yml??

**Comment by sgdc3** [comment]
```

Email:
    # Email SMTP server host
    mailSMTP: smtp.gmail.com
    # Email SMTP server port
    mailPort: 465
    # Email account that send the mail
    mailAccount: ''
    # Email account password
    mailPassword: ''
    # Custom SenderName, that replace the mailAccount name in the email
    mailSenderName: ''
    # Random password length
    RecoveryPasswordLength: 8
    # Email subject of password get
    mailSubject: 'Your new AuthMe Password'
    # Like maxRegPerIp but with email
    maxRegPerEmail: 1
    # Recall players to add an email?
    recallPlayers: false
    # Delay in minute for the recall scheduler
    delayRecall: 5
    # Blacklist these domains for emails
    emailBlacklisted:
    - 10minutemail.com
    # WhiteList only these domains for emails
    emailWhitelisted: []
    # Do we need to send new password draw in an image?
    generateImage: false
    # The email OAuth 2 token (leave empty if not used)
    emailOauth2Token: ''
```
Just read the comments xD
