### ISSUE TITLE
[Dev] Support comments on config sections

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#516]
With `NewSetting` and `SettingsClass` implementations we can write comments in config.yml for properties with `@Comment`, but not above sections:

```yml
settings:
    section1:
        # This is a property so we can do a comment here, but not above
        setting: false
```

Implement a way to add such comments. Annotations at type level would be nice but we can only add one annotation per element. Since all settings classes implement `SettingsClass` we could put a method `Map<String, String> getSectionComments()` on there, for example.

Parts:
- Implementation
- Unit test (only one class can define a section, or at least a _comment_ for a section)
- Create a tools task to generate the config.yml (or, minimally, create another issue)
