### ISSUE TITLE
A new messages_zhhk.yml

### ISSUE THREAD

**Issue by i998979** [Xephi/AuthMeReloaded#521]
I don't know where to put this, so I put it here
I saw the old messages_zhhk.yml has a lot of useless sentences
so I made a new one for you.
In this messages_zhhk.yml, I removed a lot of repeat messages
also, the old one has few advertisement of his own organisation.

the files is inside the attached file (github don't let me to put .yml as attach...)

```
#----------------------------------------#
#translated by i998979
#----------------------------------------#
unknown_user: '&f用戶資料並不存在於資料庫中。'
unsafe_spawn: '&f你的登出的位置不安全，將傳送你至重生點。'
not_logged_in: '&c你並未登入！'
reg_voluntarily: '&f請使用: /register <密碼> <重覆密碼> 來註冊。'
usage_log: '&c用法: /login <密碼>'
wrong_pwd: '&c密碼錯誤。'
unregistered: '&c成功取消該名用戶的註冊記錄。'
reg_disabled: '&c新玩家註冊已停用。'
valid_session: '&cIP記憶，自動登入。'
login: '&c登入成功。'
vb_nonActiv: '&f你的帳戶並未啟用，請檢查你的電郵！'
user_regged: '&c此用戶名已有註冊記錄。'
usage_reg: '&c用法: /register <密碼> <重覆密碼>'
max_reg: '&f你的IP地址已達到註冊帳號上限。'
no_perm: '&c你沒有足夠的權限。'
error: '&f發生錯誤，請與管理員聯絡。'
login_msg: '&c請使用 /login <密碼> 來登入。'
reg_msg: '&c請使用 /register <密碼> <重覆密碼> 來註冊。'
reg_email_msg: '&c請使用 /register <電郵> <重覆電郵> 來註冊。'
usage_unreg: '&c用法: /unregister <密碼>'
pwd_changed: '&c密碼更改成功！'
user_unknown: '&c該用戶並未註冊。'
password_error: '&f密碼不符合。'
password_error_nick: '&f你不能使用你的名字作為密碼。'
password_error_unsafe: '&f你不能使用安全性過低的碼。'
invalid_session: '&f登入階段資料不相同，請等待登入階段結束。'
reg_only: '&f只限已註冊用戶，請先到 https://www.example.com 註冊。'
logged_in: '&c你已經登入過了。'
logout: '&b登出成功。'
same_nick: '&f同名玩家已在遊玩。'
registered: '&b註冊成功。'
pass_len: '&f你的密碼太短或太長。'
reload: '&b系統設定及資料庫已重新載入。'
timeout: '&f登入逾時，請重新登入。'
usage_changepassword: '&f用法: /changepassword <舊密碼> <新密碼>'
name_len: '&c你的用戶名太短或太長。'
regex: '&c你的用戶名含有不容許的字符。以下為准許之字母: REG_EX。'
add_email: '&b請為你的帳戶添加電郵地址: /email add <電郵地址> <重覆電郵地址>。'
bad_database_email: '/email 只適用於使用MySQL或SQLite之伺服器，請聯絡管理員。'
recovery_email: '&c忘記密碼？請使用 /email recovery <電郵地址> 來更新密碼。'
usage_captcha: '&c用法: /captcha <驗證碼>'
wrong_captcha: '&c驗證碼錯誤，請再次輸入 /captcha <驗證碼>。'
valid_captcha: '&c驗證碼無效！'
kick_forvip: '&cVIP玩家登入了滿人的伺服器。'
kick_fullserver: '&c因為伺服器滿人，請稍候再試。'
usage_email_add: '&f用法: /email add <電郵> <重覆電郵>'
usage_email_change: '&f用法: /email change <舊電郵> <新電郵>'
usage_email_recovery: '&f用法: /email recovery <電郵>'
new_email_invalid: '新電郵地址不正確。'
old_email_invalid: '舊電郵地址不正確。'
email_invalid: '電郵地址不正確。'
email_added: '電郵地址已加入。'
email_confirm: '請確認電郵地址。'
email_changed: '電郵地址已更改。'
email_send: '已寄出忘記密碼信件。'
country_banned: '你的國家已被本伺服器封禁。'
antibot_auto_enabled: '防止機械人程序因大量不尋常連線而啟用。'
antibot_auto_disabled: '防止機械人程序將於 %m 分鐘後停止運作。'
```

**Comment by sgdc3** [comment]
Done! Thanks ;)

**Comment by ljacqu** [comment]
@i998979 Thanks for the contribution! Could we ask you to translate the following as well? :) Then we have a complete zhcn file.

```yml
email_already_used: '&4The email address is already being used'
kick_antibot: 'AntiBot protection mode is enabled! You have to wait some minutes before joining the server.'
email_exists: '&cA recovery email was already sent! You can discard it and send a new one using the command below:'
two_factor_create: '&2Your secret code is %code. You can scan it from here: %url'
```

Also, in `wrong_captcha`, we use the placeholder `THE_CAPTCHA` to replace it with the actual captcha code. Maybe you could help us integrate it into the message. Would it just be this?
```diff
- wrong_captcha: '&c驗證碼錯誤，請再次輸入 /captcha <驗證碼>。'
+ wrong_captcha: '&c驗證碼錯誤，請再次輸入 /captcha THE_CAPTCHA。'
```
