### ISSUE TITLE
Configure AuthMe being optional

### ISSUE THREAD

**Issue by EvilOlaf** [Xephi/AuthMeReloaded#611]
Hey there,

my idea was to use AuthMe as additional security layer for an online mode server.
Basically the registration should be completely optional. So all server features can be used unrestricted as AuthMe is entirely passive.

When a user decides to register with AuthMe, it will come into place and force a user after the next login to provide the proper password to be able to move, chat or whatever. All the stuff that AuthMe prevents from being executed when a user is not logged in.

So how would that increase security if it is optional?

Well actually Minecraft in online mode is pretty secure, but there are situations where you wish to have an additional layer of security which you can control personally. For example one of two siblings are is a team mate and share the same computer. The team mate did not log out of his Minecraft account and, well...everything is possible from this point.
There also other quite rare situations where an additional layer of security can help, like stolen login credentials from Mojang or hijacked sessions.

Unfortunately I was not able to configure AuthMe as described above yet...honestly unsure if it is even possible this way.

Thanks for reading.

**Comment by ljacqu** [comment]
Hi @EvilOlaf,

Thanks a lot for the detailed description. I wonder if it would suffice to set the following two values in your config.yml:

```yml
    registration: 
        # Only registered and logged in players can play.
        # See restrictions for exceptions
        force: false

# Somewhere else below
        allowAllCommandsIfRegistrationIsOptional: true
```

If not, this is basically a bug report and we need to fix whatever hinders unregistered players from playing normally with those settings.
