### ISSUE TITLE
problem with chars!

### ISSUE THREAD

**Issue by rErEaT** [Xephi/AuthMeReloaded#640]
I cant join if my name contains on of this: űáéőúóüö
and same as password :/

can you fix this?

**Comment by sgdc3** [comment]
Can you post your config please? ;)

**Comment by rErEaT** [comment]
yes

here is it:
http://pastebin.com/ygJ1jCwC

**Comment by rErEaT** [comment]
yes and I am using the AuthMe-v5.2-SNAPSHOT-b905 version

**Comment by sgdc3** [comment]
```YAML
...
        # Regex syntax for allowed chars in passwords
        allowedPasswordCharacters: '[a-zA-Z0-9_?!@+&-]*'
...

        # Regex syntax of allowed characters in the player name.
        allowedNicknameCharacters: '[a-zA-Z0-9_]*'
...
```
