### ISSUE TITLE
[Dev] Test: CommandDescription objects and plugin.yml must correspond

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#742]
The labels in parent `CommandDescription` objects (e.g. for /authme or /register) must also be present in the project's plugin.yml or they won't be picked up by Bukkit. Create a unit test that verifies this.

plugin.yml can be loaded with Bukkit's `YamlConfiguration`. The first-level key under `commands` is the main label and the rest is under `aliases`; the labels of a CommandDescription should have exactly that list.

Excerpt plugin.yml:
```yml
commands:
    register:
        description: Register an account
        usage: /register <password> <confirmpassword>
        aliases: [reg]
    login:
        description: Login command
        usage: /login <password>
        aliases: [l,log]
```

Excerpt CommandInitializer:
```java
        final CommandDescription REGISTER_BASE = CommandDescription.builder()
            .parent(null)
            .labels("register", "reg")
             // ...
            .build();
        final CommandDescription LOGIN_BASE = CommandDescription.builder()
            .parent(null)
            .labels("login", "l")  // <-- Ha, I make an example and find a mismatch
            // Reason for a unit test CONFIRMED
            .build();
```
