### ISSUE TITLE
Captcha bug return

### ISSUE THREAD

**Issue by Kixot14** [Xephi/AuthMeReloaded#747]
Looks like this don't fixed https://github.com/Xephi/AuthMeReloaded/issues/322

If **maxLoginTry = 5**, i can 5 times enter the wrong password, and then i have last 6-th try, after which AuthMe show me captcha. But this 6-th try will be always wrong for AuthMe, even if password correct!

AuthMe build: #1093
Spigot build: #847

**Comment by sgdc3** [comment]
@Xephi

**Comment by ljacqu** [comment]
Hmm, I basically undid the solution "for" #322 (a212a0c0fd9aaeb078e492c3222e9e032cb61539) when I did #601. But I don't agree that this is a bug. For example:

```yml
    captcha:
        # Enable captcha when a player uses wrong password too many times
        useCaptcha: true
        # Max allowed tries before a captcha is required
        maxLoginTry: 2
```
"Max allowed tries *before* a captcha is required" -> You do not get a sixth try without captcha.

Ex:
```
# login tries = 0
/login wrong
> "Wrong password, please try again" // login tries = 1
/login wrong
> "Wrong password, please try again" // login tries = 2
/login correct
-> Captcha, because login tries = 2 ≥ maxLoginTry
```

What do you think, @Kixot14?
