### ISSUE TITLE
Broken Email in the latest versions.

### ISSUE THREAD

**Issue by DardBrinza** [Xephi/AuthMeReloaded#819]
Auto-remove message in config, not generated password, not displayed nickname.

Screenshot messages that came in the mail:
http://dl2.joxi.net/drive/2016/07/02/0002/2579/178707/07/b56edc8ed7.png

```
Email: 
    # Email SMTP server host
    mailSMTP: 'smtp.yandex.ru'
    # Email SMTP server port
    mailPort: 25
    # Email account which sends the mails
    mailAccount: 'mail@.ru'
    # Email account password
    mailPassword: 'pass1337'
    # Custom sender name, replacing the mailAccount name in the email
    mailSenderName: 'None'
    # Recovery password length
    RecoveryPasswordLength: 6
    # Mail Subject
    mailSubject: 'Restore Acc'
    # Like maxRegPerIP but with email
    maxRegPerEmail: 5
    # Recall players to add an email?
    recallPlayers: false
    # Delay in minute for the recall scheduler
    delayRecall: 5
    # Blacklist these domains for emails
    emailBlacklisted: []
    # Whitelist ONLY these domains for emails
    emailWhitelisted: []
    # Send the new password drawn in an image?
    generateImage: false
    # The OAuth2 token
    emailOauth2Token: ''
```
