### ISSUE TITLE
ForceSpawnLocOnJoin not working

### ISSUE THREAD

**Issue by Mormaii** [Xephi/AuthMeReloaded#838]
Using latest dev build from Jenkins

```
SaveQuitLocation: false
ForceSpawnLocOnJoin: 
  enabled: true
  worlds:
  - 'Hub'
```

Doing /logout and /login doesn't teleport me to the spawn. Also disconnecting and reconnecting it won't teleport me to the spawn either, even after a server restart it just keep the last logout location. I'm using multiverse.

```
firstspawnoverride: 'true'
firstspawnworld: Hub

```
