### ISSUE TITLE
Country Protection

### ISSUE THREAD

**Issue by QIIxGriimZzQ** [Xephi/AuthMeReloaded#860]
Today, a new player came on the server with IP anonymous and the US, but I got these country on blacklist. I tried add to the blacklist my country (CZ), but I still could join.
And can I prevent duplicate player names? (IIxGriimZz, iiXgRiimZZ)

I tried last version: 5.2
And devbuild: 1220
Spigot 1.8.7

**Comment by sgdc3** [comment]
About the duplicate names: preventOtherCase: true

**Comment by sgdc3** [comment]
@DNx5 Any idea about the geoip issue?

**Comment by sgdc3** [comment]
@QIIxGriimZzQ Could you post your config?

**Comment by QIIxGriimZzQ** [comment]
My config now: http://pastebin.com/FBYdkWpQ
I tried again add to the blacklist my country, in Minecraft menu, where you see all servers i saw message like "Your country is banned...", but I still could join...

**Comment by sgdc3** [comment]
> i saw message like "Your country is banned.
This means that you are not using latest build. The modified message in server list have been removed.

**Comment by QIIxGriimZzQ** [comment]
Sorry for the confusion. I have AuthMe 5.2 BETA3 version (with message) on my first server.
And now i have build 1220 on my second server. There was not a message, but i still could join.

**Comment by sgdc3** [comment]
@QIIxGriimZzQ There is a new option now: enableProtectionRegistered
You need to keep it enabled. ;)

**Comment by QIIxGriimZzQ** [comment]
I looked at this:
https://github.com/AuthMe/AuthMeReloaded/blob/master/src/main/resources/config.yml
As you write, there is a new option. But in config no. I deleted the old config but in new config is just (build 1220):
```
`Protection: 
    # Enable some servers protection (country based login, antibot)
    enableProtection: false
    # Countries allowed to join the server and register, see http://dev.bukkit.org/bukkit-plugins/authme-reloaded/pages/countries-codes/ for countries' codes
    # PLEASE USE QUOTES!
    countries: 
    - 'US'
    - 'GB'
    # Countries not allowed to join the server and register
    # PLEASE USE QUOTES!
    countriesBlacklist: 
    - 'A1'
    # Do we need to enable automatic antibot system?
    enableAntiBot: true
    # Max number of players allowed to login in 5 secs before the AntiBot system is enabled automatically
    antiBotSensibility: 10
    # Duration in minutes of the antibot automatic system
    antiBotDuration: 10 `

```

I tried to rewrite config on this (but I still could join):
```
`Protection:
    # Enable some servers protection ( country based login, antibot )
    enableProtection: true
    # Apply the protection also to registered usernames
    enableProtectionRegistered: true
    # Countries allowed to join the server and register, see http://dev.bukkit.org/bukkit-plugins/authme-reloaded/pages/countries-codes/ for countries' codes
    # PLEASE USE QUOTES!
    countries:
    - 'SK'
    # Countries blacklisted automatically (without any needed to enable protection)
    # PLEASE USE QUOTES!
    countriesBlacklist:
    - 'A1'
    - 'US'
    - 'CZ'
    # Do we need to enable automatic antibot system?
    enableAntiBot: true
    # Max number of player allowed to login in 5 secs before enable AntiBot system automatically
    antiBotSensibility: 10
    # Duration in minutes of the antibot automatic system
    antiBotDuration: 10`
```
