### ISSUE TITLE
Add option to disable PlayerCache

### ISSUE THREAD

**Issue by Twonox** [Xephi/AuthMeReloaded#880]
What is the utility of playerdata storage ?

**Comment by DNx5** [comment]
It used to save player's state (like OP, group, flying, speed, etc) so, we can restore it later when player get authenticated.

**Comment by Twonox** [comment]
But without playerdata storage, there is no problems. When I reset it I'm in my last location, I'm Op, I fly etc

**Comment by ljacqu** [comment]
Relates to #845. @DNx5 What's the strategy for updating player data?

I'm guessing we have two "incompatible" issues:
- If the server crashes and someone is unregistered, the server will remember the player with all of the restrictions that AuthMe applied to him (walking speed = 0, etc.)
- If someone is is opped / fly speed changed etc. sometime later, this will no longer be reflected in the PlayerData because once PlayerData is written to the disk, it is never updated again (see linked issue)

Please correct me if I'm wrong

**Comment by Twonox** [comment]
Yes, it's necessary to can disable playerdata.

**Comment by DNx5** [comment]
I'm worrying if I implement this, more unexpected behaviour will happen.
@ljacqu is it okay for player to have default state each time they log-in?

**Comment by ljacqu** [comment]
@DNx5 If you're up for it I'd love to have a session with you sometime to discuss about the LimboPlayer stuff. We joke that 5.3 is the translation update, but from a technical todo point of view I regard 5.3 as the limbo player update :) Do you have time to spare in this milestone for us to look at the LimboPlayer stuff?

**Comment by ljacqu** [comment]
Hi @Twonox, this should have been fixed with issue #1125 and is available in build n. 1611 or above—http://ci.xephi.fr/job/AuthMeReloaded/

Once you start the new version you should see new options in config.yml:
```yml
# Before a user logs in, various properties are temporarily removed from the player,
# such as OP status, ability to fly, and walk/fly speed.
# Once the user is logged in, we add back the properties we previously saved.
# In this section, you may define how these properties should be handled.
limbo:
    persistence:
        # Besides storing the data in memory, you can define if/how the data should be persisted
        # on disk. This is useful in case of a server crash, so next time the server starts we can
        # properly restore things like OP status, ability to fly, and walk/fly speed.
        # DISABLED: no disk storage, INDIVIDUAL_FILES: each player data in its own file,
        # SINGLE_FILE: all data in one single file (only if you have a small server!)
        # SEGMENT_FILES: distributes players into different buckets based on their UUID. See below.
        type: 'SEGMENT_FILES'
        # This setting only affects SEGMENT_FILES persistence. The segment file
        # persistence attempts to reduce the number of files by distributing players into various
        # buckets based on their UUID. This setting defines into how many files the players should
        # be distributed. Possible values: ONE, TWO, FOUR, EIGHT, SIXTEEN, THIRTY_TWO, SIXTY_FOUR,
        # ONE_TWENTY for 128, TWO_FIFTY for 256.
        # For example, if you expect 100 non-logged in players, setting to SIXTEEN will average
        # 6.25 players per file (100 / 16). If you set to ONE, like persistence SINGLE_FILE, only
        # one file will be used. Contrary to SINGLE_FILE, it won't keep the entries in cache, which
        # may deliver different results in terms of performance.
        # Note: if you change this setting you lose all stored LimboPlayer data because the
        # distribution of players will be different.
        segmentDistribution: 'THIRTY_TWO'
```

You know how it goes: please let us know if this makes it OK to close this issue, or kindly let us know if you think something is missing :)
